### ISSUE TITLE
Next step after installation missing

### ISSUE THREAD

**Issue by Fuzzyma** [ilyachch/md_docs-trans-app#17]
I installed this package with the pip command of the readme on a windows machine.

And what now? Just typing `app.py` into my terminal yields nothing (I doubt that my path variable was updated anyway). Using `./app.py` only looks into the current folder, so does `python app.py`.

So what I am supposed to do? Do I have to cd into the directory where all pip packages are installed? Why then even bother installing it with pip (I could just have cloned the repo).

Please enlighten me, I am stuck!

**Comment by ilyachch** [comment]
@Fuzzyma 
Hello! I'm very sorry for SO long pause.
If it is still actual for you, I remade project and fixed documentation issue
