### ISSUE TITLE
Can you add an option to support adding the translation to a new file?

### ISSUE THREAD

**Issue by hengzhe-zhang** [ilyachch/md_docs-trans-app#23]
I find that this tool is very useful because I need to synchronize documents between different languages. However, the current version is not very convenient because I need to separate the translated text from the original text manually. Can you add an option to support adding the translation to a new file?

**Comment by ilyachch** [comment]
yeah, sure. But it will be optional flag

**Comment by anthares101** [comment]
@zhenlingcn i modified the file_translator.py a bit to put the translation to another file called `Translation.md`. If a line is code or cant be translated it just let the original one.

Here it is the code:

```python
from pathlib import Path
from typing import IO, TYPE_CHECKING, Any, List

from md_translate.line_processor import Line
from md_translate.logs import logger

if TYPE_CHECKING:
    from md_translate.settings import Settings


class FileTranslator:
    default_open_mode: str = 'r+'

    def __init__(self, settings: 'Settings', file_path: Path) -> None:
        self.settings = settings
        self.file_path: Path = file_path
        self.file_contents_with_translation: list = []
        self.code_block: bool = False

    def __enter__(self) -> 'FileTranslator':
        self.__translating_file: IO = self.file_path.open(self.default_open_mode)
        self.__translated_file: IO = open("Translation.md", "w")
        return self

    def __exit__(self, *args: Any, **kwargs: Any) -> None:
        self.__translating_file.close()

    def translate(self) -> None:
        lines = self._get_lines()
        for counter, _line in enumerate(lines):
            line = Line(self.settings, _line)
            self.code_block = (
                not self.code_block if line.is_code_block_border() else self.code_block
            )
            if line.can_be_translated() and not self.code_block:
                self.file_contents_with_translation.append(line.fixed)
                logger.info(f'Processed {counter+1} lines')
            else:
                self.file_contents_with_translation.append(line.original)
        self._write_translated_data_to_file()

    def _get_lines(self) -> List[str]:
        lines = self.__translating_file.readlines()
        logger.info(f'Got {len(lines)} lines to process')
        return lines

    def _write_translated_data_to_file(self) -> None:
        self.__translated_file.seek(0)
        self.__translated_file.writelines(self.file_contents_with_translation)
```

@ilyachch i know is not "pretty" but could be an initial idea of how to implement that optional flag :smile:

**Comment by ilyachch** [comment]
I've made a lot of changes under the hood, moved much more responsibilities to `Line` class.
So, now it's more easy to implement it=)

@anthares101 In your snippet, as I can see, the original file will be overwritten. I think it's not the best solution (machine translation is not perfect yet) but thoughts in the right direction.

And, also, if you are using git for managing translating files, it will be much easier to find new lines=)

**Comment by anthares101** [comment]
@ilyachch The original is not overwritten! I created a new object `__translated_file` for the translated content and the program only reads from the original file.

This changes made my work easier but I got your point about having all the content in the same file to track changes :D

**Comment by ilyachch** [comment]
Oh, I was seeing in wrong place! My fault!
Yeah, you a correct

if you do not mind, I'll invite you in PR with separate file writing, when it's ready?

**Comment by anthares101** [comment]
Yeah, no problem ^^

**Comment by ilyachch** [comment]
made in #28
