### ISSUE TITLE
Please  support for annotation blocks inside dashes (---)

### ISSUE THREAD

**Issue by kevinz** [ilyachch/md_docs-trans-app#58]
Thanks for the great tool,can you please support for skipping annotation blocks inside dashes (---), for example in https://github.com/backstage/backstage/blob/master/docs/faq/index.md?plain=1

**Comment by ilyachch** [comment]
@kevinz 

As I can see, this kind of annotations is not a part of standard Markdown syntax. I can suggest to add some kind of comment to mark block, that have to be ignored.
Something like:
```
<!-- md_translate: ignore on -->

This text will be ignored

<!-- md_translate: ignore off -->
```
